version: '3.8'

services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-service
    networks:
      - bank_network
    ports:
      - "3000:3000"

networks:
  bank_network:
    external: true
